from io import BytesIO

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from docx import Document

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from app.database import get_db
from app.models.audit_log import AuditLog
from app.models.user import User

from app.schemas.audit_log import (
    AuditLogResponse,
    AuditLogListResponse
)

from app.dependencies.auth import require_role

router = APIRouter(
    prefix="/audit-logs",
    tags=["Audit Logs"]
)


@router.get(
    "/",
    response_model=AuditLogListResponse
)
def get_audit_logs(
    page: int = Query(1, ge=1),
    limit: int = Query(10, ge=1, le=100),
    search: str | None = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_role(["Admin"])
    )
):
    offset = (page - 1) * limit

    # ================= QUERY =================

    query = (
        db.query(AuditLog)
        .order_by(AuditLog.created_at.desc())
    )

    # ================= SEARCH =================

    if search:
        search_value = f"%{search.strip()}%"

        query = query.filter(
            AuditLog.user_name.ilike(search_value)
            | AuditLog.action.ilike(search_value)
            | AuditLog.description.ilike(search_value)
        )

    # ================= TOTAL =================

    total = query.count()

    # ================= PAGINATION =================

    audit_logs = (
        query
        .offset(offset)
        .limit(limit)
        .all()
    )

    # ================= RESPONSE =================

    return {
        "page": page,
        "limit": limit,
        "total": total,
        "total_pages": (total + limit - 1) // limit,
        "audit_logs": audit_logs
    }
    
    
    # ================= EXPORT AUDIT LOGS AS DOCX =================

@router.get("/export/docx")
def export_audit_logs_docx(
    search: str | None = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_role(["Admin"])
    )
):
    # ================= QUERY =================

    query = (
        db.query(AuditLog)
        .order_by(AuditLog.created_at.desc())
    )

    # ================= SEARCH =================

    if search:
        search_value = f"%{search.strip()}%"

        query = query.filter(
            AuditLog.user_name.ilike(search_value)
            | AuditLog.action.ilike(search_value)
            | AuditLog.description.ilike(search_value)
        )

    audit_logs = query.all()

    # ================= CREATE DOCUMENT =================

    document = Document()

    # Title

    title = document.add_heading(
        "Audit Logs",
        level=0
    )

    # Description

    document.add_paragraph(
        "Employee Management System"
    )

    document.add_paragraph(
        f"Generated by: {current_user.name}"
    )

    document.add_paragraph(
        f"Total activities: {len(audit_logs)}"
    )

    # ================= TABLE =================

    table = document.add_table(
        rows=1,
        cols=6
    )

    table.style = "Table Grid"

    header_cells = table.rows[0].cells

    header_cells[0].text = "User"
    header_cells[1].text = "Role"
    header_cells[2].text = "Action"
    header_cells[3].text = "Details"
    header_cells[4].text = "Target"
    header_cells[5].text = "Date & Time"

    # ================= TABLE DATA =================

    for log in audit_logs:

        row_cells = table.add_row().cells

        row_cells[0].text = log.user_name or "Unknown"
        row_cells[1].text = log.role or "—"
        row_cells[2].text = log.action or "—"
        row_cells[3].text = log.description or "—"

        if log.target_type:

            if log.target_id is not None:
                target = f"{log.target_type} #{log.target_id}"
            else:
                target = log.target_type

        else:
            target = "—"

        row_cells[4].text = target

        if log.created_at:
            row_cells[5].text = log.created_at.strftime(
                "%d %b %Y, %I:%M %p"
            )
        else:
            row_cells[5].text = "—"

    # ================= SAVE TO MEMORY =================

    file_stream = BytesIO()

    document.save(file_stream)

    file_stream.seek(0)

    # ================= DOWNLOAD =================

    return StreamingResponse(
        file_stream,
        media_type=(
            "application/vnd.openxmlformats-officedocument."
            "wordprocessingml.document"
        ),
        headers={
            "Content-Disposition": (
                'attachment; filename="audit_logs.docx"'
            )
        }
    )
    
    
    # ================= EXPORT AUDIT LOGS AS PDF =================

@router.get("/export/pdf")
def export_audit_logs_pdf(
    search: str | None = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(
        require_role(["Admin"])
    )
):
    # ================= QUERY =================

    query = (
        db.query(AuditLog)
        .order_by(AuditLog.created_at.desc())
    )

    # ================= SEARCH =================

    if search:
        search_value = f"%{search.strip()}%"

        query = query.filter(
            AuditLog.user_name.ilike(search_value)
            | AuditLog.action.ilike(search_value)
            | AuditLog.description.ilike(search_value)
        )

    audit_logs = query.all()

    # ================= PDF SETUP =================

    file_stream = BytesIO()

    document = SimpleDocTemplate(
        file_stream,
        pagesize=landscape(A4),
        rightMargin=12 * mm,
        leftMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    normal_style = styles["Normal"]

    elements = []

    # ================= HEADER =================

    elements.append(
        Paragraph(
            "Audit Logs",
            title_style
        )
    )

    elements.append(
        Paragraph(
            "Employee Management System",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            f"Generated by: {current_user.name}",
            normal_style
        )
    )

    elements.append(
        Paragraph(
            f"Total activities: {len(audit_logs)}",
            normal_style
        )
    )

    elements.append(
        Spacer(1, 8 * mm)
    )

    # ================= TABLE DATA =================

    table_data = [
        [
            "User",
            "Role",
            "Action",
            "Details",
            "Target",
            "Date & Time",
        ]
    ]

    for log in audit_logs:

        if log.target_type:

            if log.target_id is not None:
                target = f"{log.target_type} #{log.target_id}"
            else:
                target = log.target_type

        else:
            target = "—"

        if log.created_at:
            created_at = log.created_at.strftime(
                "%d %b %Y, %I:%M %p"
            )
        else:
            created_at = "—"

        table_data.append(
            [
                log.user_name or "Unknown",
                log.role or "—",
                log.action or "—",
                log.description or "—",
                target,
                created_at,
            ]
        )

    # ================= TABLE =================

    table = Table(
        table_data,
        repeatRows=1,
        colWidths=[
            28 * mm,
            22 * mm,
            32 * mm,
            80 * mm,
            35 * mm,
            38 * mm,
        ],
    )

    table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#23436F"),
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "FONTSIZE",
                    (0, 0),
                    (-1, 0),
                    8,
                ),
                (
                    "FONTSIZE",
                    (0, 1),
                    (-1, -1),
                    7,
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.4,
                    colors.HexColor("#CBD5E1"),
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP",
                ),
                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
            ]
        )
    )

    elements.append(table)

    # ================= BUILD PDF =================

    document.build(elements)

    file_stream.seek(0)

    # ================= DOWNLOAD =================

    return StreamingResponse(
        file_stream,
        media_type="application/pdf",
        headers={
            "Content-Disposition": (
                'attachment; filename="audit_logs.pdf"'
            )
        },
    )