"""add employee active status

Revision ID: c51a0411e144
Revises: b1ae1783225a
Create Date: 2026-08-18 12:05:13.518530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51a0411e144'
down_revision: Union[str, Sequence[str], None] = 'b1ae1783225a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "employees",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=True
        )
    )

    op.execute(
        "UPDATE employees SET is_active = TRUE WHERE is_active IS NULL"
    )

    op.alter_column(
        "employees",
        "is_active",
        existing_type=sa.Boolean(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_active')
    # ### end Alembic commands ###
